### ISSUE TITLE
export stack file from Docker Cloud

### ISSUE THREAD

**Issue by anas-aso** [docker/dockercloud-cli#16]
I exported the current running stackfiles from Docker Cloud account and I got a file with all the indentations missed up

**Comment by tifayuki** [comment]
@anas-aso 
Which OS are you on? 
I tested it on both OS X and Ubuntu, and it works fine.

**Comment by anas-aso** [comment]
@tifayuki I'm using OS X 10.11.3 (15D21)
I wanted to try it again now and I got this famous error message : 
```bash
$ docker-cloud stack ls
Status 429 (GET https://cloud.docker.com/api/tutum/v1/auth/). Response: {"detail": "Too many login attempts."}
```

**Comment by fermayo** [comment]
@tifayuki I also have the problem, OS X

**Comment by fermayo** [comment]
@anas-aso can you please provide the exported docker-compose that you get?

**Comment by anas-aso** [comment]
@fermayo there is nothing special about it, but here it is : 
```yaml
lb:
  image: 'dockercloud/haproxy:1.0.1'
  autoredeploy: true
  links:
    - web-site
  ports:
    - '80:80'
    - '443:443'
  restart: always
  roles:
    - global
  sequential_deployment: true
web-site:
  image: 'tutum/hello-world:latest'
  autoredeploy: true
  restart: always
  sequential_deployment: true
```
and this is what I got after exporting it from Docker Cloud
```yaml
lb:
  autoredeploy: true
  image: dockercloud/haproxy:1.0.1
  links:
  - web-site
  ports:
  - 80:80
  - 443:443
  restart: always
  roles:
  - global
  sequential_deployment: true
web-site:
  autoredeploy: true
  image: tutum/hello-world:latest
  restart: always
  sequential_deployment: true
```
You see here that the indentation was missed up for links, ports and roles values
and this is the docker-cloud version I'm using : 
```bash
$ docker-cloud --version
docker-cloud 1.0.1
```
