### ISSUE TITLE
docker-cloud create fails, while pasting it in UI succeeds

### ISSUE THREAD

**Issue by peterlauri** [docker/dockercloud-cli#17]
Information here:

https://forums.docker.com/t/docker-cloud-stack-complains-about-bad-format/8422/1

**Comment by peterlauri** [comment]
I installed the latest version from master commit d2e86e3 locally.

docker-cloud-bug.yml
```
someservice:
  image: ubuntu
  environment:
    SOME_COOL_ENV: "db286f7=15)#33$3(n(uq*(q4)ohcn!sx(gs^i#0%1t7j$t3#2"
```

And then when running stack create:

```
✗ .vedockercloud/bin/docker-cloud stack create -n bug -f docker-cloud-bug.yml
Bad format of the stack file(docker-cloud-bug.yml): Invalid interpolation format for "environment" option in service "someservice": "db286f7=15)#33$3(n(uq*(q4)ohcn!sx(gs^i#0%1t7j$t3#2"
```
