### ISSUE TITLE
mount (volumes) not allowed for files – only directorys

### ISSUE THREAD

**Issue by jekkos** [docker/dockercloud-cli#29]
When trying to deploy a stack with mysql image, I want to mount just one file (sql script) inside of the mysql docker container. This web:
   
works both in docker and docker-compose, but not in docker-cloud.

Instead it just create a directory

```
mysql:
    image: mysql:5.6
    ports:
        - 3306:3306
    volumes:
        - /app/database/database.sql:/docker-entrypoint-initdb.d/database.sql
```

See also docker/compose#424
